<a href="https://colab.research.google.com/github/GinnaGomez09/proyecto_aplicado_javeriana/blob/main/notebooks/08_integracion_tcac.ipynb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# ============================================================
# Clonar repositorio y preparar entorno
# ============================================================

!git clone https://github.com/GinnaGomez09/proyecto_aplicado_javeriana.git
%cd proyecto_aplicado_javeriana

Cloning into 'proyecto_aplicado_javeriana'...
remote: Enumerating objects: 474, done.
remote: Counting objects: 100% (210/210), done.
remote: Compressing objects: 100% (143/143), done.
remote: Total 474 (delta 164), reused 66 (delta 66), pack-reused 264 (from 2)
Receiving objects: 100% (474/474), 4.48 MiB | 14.13 MiB/s, done.
Resolving deltas: 100% (262/262), done.
/content/proyecto_aplicado_javeriana

In [3]:
# ------------------------------------------------------------
# 1. Cargar ingredientes convertidos
# ------------------------------------------------------------

import pandas as pd

input_recetas = "data/interim/recetas_unidades_convertidas.csv"

ingredientes = pd.read_csv(input_recetas)

print("Dimensiones ingredientes:", ingredientes.shape)
print("Número de recetas:", ingredientes["recipe_id"].nunique())

ingredientes.head()

Dimensiones ingredientes: (3777, 18)
Número de recetas: 436

,recipe_id,recipe_title,ingredient_id,original_text,clean_text,ingredient_name_clean,unit_clean,quantity_original,quantity_value,unit_extracted,ingredient_extracted,preparation_state,metric_equivalent_value,metric_equivalent_unit,ingredient_standardized,metric_quantity_value,metric_quantity_unit,conversion_method
0,86af61e4-e16a-11ed-9591-a96d6180cd25,Arepas de Queso,1,1 taza de harina de arepa blanca o amarilla,1 taza de harina de arepa blanca o amarilla,harina de arepa blanca o amarilla,taza,1,1.000000,taza,harina de arepa blanca o amarilla,NaN,NaN,NaN,harina de arepa,132.0,g,conversion_volumen_a_gramos_por_densidad
1,86af61e4-e16a-11ed-9591-a96d6180cd25,Arepas de Queso,2,1 taza de agua tibia,1 taza de agua tibia,agua tibia,taza,1,1.000000,taza,agua,tibia,NaN,NaN,agua,240.0,g,conversion_volumen_a_gramos_por_densidad
2,86af61e4-e16a-11ed-9591-a96d6180cd25,Arepas de Queso,3,⅓ taza de queso mozzarella o queso blanco rallado,1/3 taza de queso mozzarella o queso blanco ra...,queso mozzarella o queso blanco rallado,taza,1/3,0.333333,taza,queso mozzarella o queso blanco,rallado,NaN,NaN,queso mozzarella,48.0,g,conversion_volumen_a_gramos_por_densidad
3,86af61e4-e16a-11ed-9591-a96d6180cd25,Arepas de Queso,4,2 cucharadas de mantequilla,2 cucharadas de mantequilla,mantequilla,cucharada,2,2.000000,cucharadas,mantequilla,NaN,NaN,NaN,mantequilla,28.8,g,conversion_volumen_a_gramos_por_densidad
4,86af61e4-e16a-11ed-9591-a96d6180cd25,Arepas de Queso,5,Sal,sal,sal,NaN,1,1.000000,unidad,sal,NaN,NaN,NaN,sal,NaN,NaN,sin_conversion

In [4]:
# ------------------------------------------------------------
# 2. Cargar TCAC
# ------------------------------------------------------------

input_tcac = "data/raw/tcac/tcac.csv"

tcac = pd.read_csv(input_tcac)

print("Dimensiones TCAC:", tcac.shape)

tcac.head()

Dimensiones TCAC: (773, 41)

,grupo_Alimento,codigo,nombre_alimento,parte_analizada,humedad_g,energia_kcal,energia_kj,proteina_g,lipidos_g,carbohidratos_totales_g,...,colesterol_mg,parte_comestible_pct,puntaje_positivo,puntaje_negativo,carga_nutricional_nrf,ratio_carbo_fibra,calidad_carbo_fibra,ratio_grasas_saludables,calidad_grasa,Energía (kcal)
0,Cereales_Derivados,A001,"Almidón de maíz, crudo",NaN,8.0,370.0,1571,0.3,0.1,91.4,...,0.0,100.0,7.524025,0.0,7.524025,101.555556,Baja (Refinado),0.0,Baja (Proaterogénica),NaN
1,Cereales_Derivados,A002,"Almojábana, bogotana, horneada",NaN,41.3,285.0,1196,13.0,12.3,30.6,...,NaN,100.0,62.837607,0.0,62.837607,NaN,Baja (Sin Fibra),NaN,NaN,NaN
2,Cereales_Derivados,A003,"Almojábana, vallecaucana, horneada",NaN,29.1,341.0,1430,17.5,14.7,34.6,...,NaN,100.0,85.683761,0.0,85.683761,NaN,Baja (Sin Fibra),NaN,NaN,NaN
3,Cereales_Derivados,A004,"Arepa de maíz precocido, con sal",NaN,60.3,163.0,690,3.3,0.9,35.0,...,NaN,100.0,22.562032,0.0,22.562032,38.888889,Baja (Refinado),NaN,NaN,NaN
4,Cereales_Derivados,A005,"Arepa de maíz precocido, sin sal",NaN,61.3,156.0,664,3.4,0.5,34.5,...,NaN,100.0,14.122396,0.0,14.122396,NaN,Baja (Sin Fibra),NaN,NaN,NaN

In [5]:
# ------------------------------------------------------------
# 3. Revisar columnas disponibles
# ------------------------------------------------------------

print("Columnas ingredientes:")
print(ingredientes.columns.tolist())

print("\nColumnas TCAC:")
print(tcac.columns.tolist())

Columnas ingredientes:
['recipe_id', 'recipe_title', 'ingredient_id', 'original_text', 'clean_text', 'ingredient_name_clean', 'unit_clean', 'quantity_original', 'quantity_value', 'unit_extracted', 'ingredient_extracted', 'preparation_state', 'metric_equivalent_value', 'metric_equivalent_unit', 'ingredient_standardized', 'metric_quantity_value', 'metric_quantity_unit', 'conversion_method']

Columnas TCAC:
['grupo_Alimento', 'codigo', 'nombre_alimento', 'parte_analizada', 'humedad_g', 'energia_kcal', 'energia_kj', 'proteina_g', 'lipidos_g', 'carbohidratos_totales_g', 'carbohidratos_disponibles_g', 'fibra_dietaria_g', 'cenizas_g', 'calcio_mg', 'hierro_mg', 'sodio_mg', 'fosforo_mg', 'yodo_mg', 'zinc_mg', 'magnesio_mg', 'potasio_mg', 'tiamina_mg', 'riboflavina_mg', 'niacina_mg', 'Folatos (mcg)', 'vitamina_b12_mcg', 'vitamina_c_mg', 'vitamina_a_er', 'grasa_saturada_g', 'grasa_monoinsaturada_g', 'grasa_poliinsaturada_g', 'colesterol_mg', 'parte_comestible_pct', 'puntaje_positivo', 'puntaje_negativo', 'carga_nutricional_nrf', 'ratio_carbo_fibra', 'calidad_carbo_fibra', 'ratio_grasas_saludables', 'calidad_grasa', 'Energía (kcal)']

In [6]:
# ------------------------------------------------------------
# 4. Definir columnas TCAC
# ------------------------------------------------------------
# Ajustar si los nombres reales cambian en tu archivo

col_tcac_codigo = "codigo"
col_tcac_nombre = "nombre_alimento"

print("Columna código TCAC:", col_tcac_codigo)
print("Columna nombre TCAC:", col_tcac_nombre)

Columna código TCAC: codigo
Columna nombre TCAC: nombre_alimento

In [7]:
# ------------------------------------------------------------
# 5. Funciones de limpieza textual
# ------------------------------------------------------------

import unicodedata
import re
import pandas as pd

def quitar_tildes(texto):
    if pd.isna(texto):
        return ""

    texto = str(texto)

    texto = unicodedata.normalize("NFD", texto)

    texto = "".join(
        c for c in texto
        if unicodedata.category(c) != "Mn"
    )

    return texto


def limpiar_texto_matching(texto):
    if pd.isna(texto):
        return ""

    texto = str(texto).lower()

    texto = quitar_tildes(texto)

    texto = re.sub(r"[^a-z0-9\s]", " ", texto)

    texto = re.sub(r"\s+", " ", texto).strip()

    return texto

In [8]:
# ------------------------------------------------------------
# 6. Limpiar ingredientes del pipeline
# ------------------------------------------------------------

import pandas as pd
import unicodedata
import re

ingredientes["ingredient_standardized_clean"] = (
    ingredientes["ingredient_standardized"]
    .apply(limpiar_texto_matching)
)

ingredientes.head()

,recipe_id,recipe_title,ingredient_id,original_text,clean_text,ingredient_name_clean,unit_clean,quantity_original,quantity_value,unit_extracted,ingredient_extracted,preparation_state,metric_equivalent_value,metric_equivalent_unit,ingredient_standardized,metric_quantity_value,metric_quantity_unit,conversion_method,ingredient_standardized_clean
0,86af61e4-e16a-11ed-9591-a96d6180cd25,Arepas de Queso,1,1 taza de harina de arepa blanca o amarilla,1 taza de harina de arepa blanca o amarilla,harina de arepa blanca o amarilla,taza,1,1.000000,taza,harina de arepa blanca o amarilla,NaN,NaN,NaN,harina de arepa,132.0,g,conversion_volumen_a_gramos_por_densidad,harina de arepa
1,86af61e4-e16a-11ed-9591-a96d6180cd25,Arepas de Queso,2,1 taza de agua tibia,1 taza de agua tibia,agua tibia,taza,1,1.000000,taza,agua,tibia,NaN,NaN,agua,240.0,g,conversion_volumen_a_gramos_por_densidad,agua
2,86af61e4-e16a-11ed-9591-a96d6180cd25,Arepas de Queso,3,⅓ taza de queso mozzarella o queso blanco rallado,1/3 taza de queso mozzarella o queso blanco ra...,queso mozzarella o queso blanco rallado,taza,1/3,0.333333,taza,queso mozzarella o queso blanco,rallado,NaN,NaN,queso mozzarella,48.0,g,conversion_volumen_a_gramos_por_densidad,queso mozzarella
3,86af61e4-e16a-11ed-9591-a96d6180cd25,Arepas de Queso,4,2 cucharadas de mantequilla,2 cucharadas de mantequilla,mantequilla,cucharada,2,2.000000,cucharadas,mantequilla,NaN,NaN,NaN,mantequilla,28.8,g,conversion_volumen_a_gramos_por_densidad,mantequilla
4,86af61e4-e16a-11ed-9591-a96d6180cd25,Arepas de Queso,5,Sal,sal,sal,NaN,1,1.000000,unidad,sal,NaN,NaN,NaN,sal,NaN,NaN,sin_conversion,sal

In [9]:
# ------------------------------------------------------------
# 7. Limpiar nombres de alimentos TCAC
# ------------------------------------------------------------

import pandas as pd
import unicodedata
import re

tcac["tcac_food_clean"] = (
    tcac[col_tcac_nombre]
    .apply(limpiar_texto_matching)
)

tcac.head()

,grupo_Alimento,codigo,nombre_alimento,parte_analizada,humedad_g,energia_kcal,energia_kj,proteina_g,lipidos_g,carbohidratos_totales_g,...,parte_comestible_pct,puntaje_positivo,puntaje_negativo,carga_nutricional_nrf,ratio_carbo_fibra,calidad_carbo_fibra,ratio_grasas_saludables,calidad_grasa,Energía (kcal),tcac_food_clean
0,Cereales_Derivados,A001,"Almidón de maíz, crudo",NaN,8.0,370.0,1571,0.3,0.1,91.4,...,100.0,7.524025,0.0,7.524025,101.555556,Baja (Refinado),0.0,Baja (Proaterogénica),NaN,almidon de maiz crudo
1,Cereales_Derivados,A002,"Almojábana, bogotana, horneada",NaN,41.3,285.0,1196,13.0,12.3,30.6,...,100.0,62.837607,0.0,62.837607,NaN,Baja (Sin Fibra),NaN,NaN,NaN,almojabana bogotana horneada
2,Cereales_Derivados,A003,"Almojábana, vallecaucana, horneada",NaN,29.1,341.0,1430,17.5,14.7,34.6,...,100.0,85.683761,0.0,85.683761,NaN,Baja (Sin Fibra),NaN,NaN,NaN,almojabana vallecaucana horneada
3,Cereales_Derivados,A004,"Arepa de maíz precocido, con sal",NaN,60.3,163.0,690,3.3,0.9,35.0,...,100.0,22.562032,0.0,22.562032,38.888889,Baja (Refinado),NaN,NaN,NaN,arepa de maiz precocido con sal
4,Cereales_Derivados,A005,"Arepa de maíz precocido, sin sal",NaN,61.3,156.0,664,3.4,0.5,34.5,...,100.0,14.122396,0.0,14.122396,NaN,Baja (Sin Fibra),NaN,NaN,NaN,arepa de maiz precocido sin sal

In [10]:
# ------------------------------------------------------------
# 8. Revisar ingredientes únicos antes del matching
# ------------------------------------------------------------

print("Ingredientes estandarizados únicos:")
print(
    ingredientes["ingredient_standardized_clean"]
    .nunique()
)

display(
    ingredientes["ingredient_standardized_clean"]
    .value_counts()
    .head(50)
)

Ingredientes estandarizados únicos:
658

ingredient_standardized_clean
cebolla                         159
sal                             149
agua                            140
sal y pimienta                  138
cilantro                        129
azucar                          119
comino                          117
ajo                             101
mantequilla                      88
aceite vegetal                   79
cebolla larga                    73
tomate                           71
papa                             69
platano                          66
leche                            65
aceite de oliva                  49
huevo                            49
extracto de vainilla             46
zanahoria                        45
queso mozzarella                 43
pimenton                         42
yuca                             39
harina de arepa                  32
achiote                          32
caldo de pollo                   30
jugo de limon                    30
crema de leche                   29
pimienta                         25
polvo de hornear                 24
canela                           22
camaron                          20
perejil                          18
mayonesa                         18
hielo                            18
azuucar                          17
caldo de carne                   17
harina                           17
arroz                            17
harina para todo uso             17
carne de res                     17
leche de coco                    16
huevo a temperatura ambiente     16
aceite                           16
vinagre                          16
pollo                            15
pimienton rojo                   15
huevo batido                     15
polvo para hornear               14
arveja                           14
coco                             14
Name: count, dtype: int64

In [11]:
# ------------------------------------------------------------
# 9. Preparar lista de alimentos TCAC
# ------------------------------------------------------------

tcac_foods = tcac["tcac_food_clean"].dropna().unique().tolist()

print("Número de alimentos TCAC:", len(tcac_foods))

Número de alimentos TCAC: 773

In [13]:
!pip install fuzzywuzzy

Collecting fuzzywuzzy
  Downloading fuzzywuzzy-0.18.0-py2.py3-none-any.whl.metadata (4.9 kB)
Downloading fuzzywuzzy-0.18.0-py2.py3-none-any.whl (18 kB)
Installing collected packages: fuzzywuzzy
Successfully installed fuzzywuzzy-0.18.0

In [14]:
# ------------------------------------------------------------
# 10. Función de matching híbrido
# ------------------------------------------------------------

import pandas as pd
from fuzzywuzzy import fuzz, process

def buscar_match_tcac(ingrediente, threshold=80):

    if pd.isna(ingrediente) or ingrediente == "":
        return None, None, None, "sin_match"

    ingrediente = str(ingrediente).strip()

    # --------------------------------------------------------
    # 1. Matching exacto
    # --------------------------------------------------------

    exacto = tcac[
        tcac["tcac_food_clean"] == ingrediente
    ]

    if not exacto.empty:

        fila = exacto.iloc[0]

        return (
            fila[col_tcac_codigo],
            fila[col_tcac_nombre],
            100,
            "exact"
        )

    # --------------------------------------------------------
    # 2. Fuzzy matching token_sort_ratio
    # --------------------------------------------------------

    resultado = process.extractOne(
        ingrediente,
        tcac_foods,
        scorer=fuzz.token_sort_ratio
    )

    if resultado:

        mejor_match, score, _ = resultado

        if score >= threshold:

            fila = tcac[
                tcac["tcac_food_clean"] == mejor_match
            ].iloc[0]

            return (
                fila[col_tcac_codigo],
                fila[col_tcac_nombre],
                score,
                "fuzzy_token_sort"
            )

    # --------------------------------------------------------
    # 3. Fuzzy matching partial_ratio
    # --------------------------------------------------------

    resultado_partial = process.extractOne(
        ingrediente,
        tcac_foods,
        scorer=fuzz.partial_ratio
    )

    if resultado_partial:

        mejor_match, score, _ = resultado_partial

        if score >= threshold:

            fila = tcac[
                tcac["tcac_food_clean"] == mejor_match
            ].iloc[0]

            return (
                fila[col_tcac_codigo],
                fila[col_tcac_nombre],
                score,
                "fuzzy_partial"
            )

    # --------------------------------------------------------
    # 4. Sin match
    # --------------------------------------------------------

    return None, None, None, "sin_match"

/usr/local/lib/python3.12/dist-packages/fuzzywuzzy/fuzz.py:11: UserWarning: Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning
  warnings.warn('Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning')

In [17]:
# Re-defining the matching function after installing fuzzywuzzy

import pandas as pd
from fuzzywuzzy import fuzz, process

def buscar_match_tcac(ingrediente, threshold=80):

    if pd.isna(ingrediente) or ingrediente == "":
        return None, None, None, "sin_match"

    ingrediente = str(ingrediente).strip()

    exacto = tcac[
        tcac["tcac_food_clean"] == ingrediente
    ]

    if not exacto.empty:

        fila = exacto.iloc[0]

        return (
            fila[col_tcac_codigo],
            fila[col_tcac_nombre],
            100,
            "exact"
        )

    resultado_token = process.extractOne(
        ingrediente,
        tcac_foods,
        scorer=fuzz.token_sort_ratio
    )

    if resultado_token and len(resultado_token) == 3: # Added length check

        mejor_match, score, _ = resultado_token

        if score >= threshold:

            fila = tcac[
                tcac["tcac_food_clean"] == mejor_match
            ].iloc[0]

            return (
                fila[col_tcac_codigo],
                fila[col_tcac_nombre],
                score,
                "fuzzy_token_sort"
            )

    resultado_partial = process.extractOne(
        ingrediente,
        tcac_foods,
        scorer=fuzz.partial_ratio
    )

    if resultado_partial and len(resultado_partial) == 3: # Added length check

        mejor_match, score, _ = resultado_partial

        if score >= threshold:

            fila = tcac[
                tcac["tcac_food_clean"] == mejor_match
            ].iloc[0]

            return (
                fila[col_tcac_codigo],
                fila[col_tcac_nombre],
                score,
                "fuzzy_partial"
            )

    return None, None, None, "sin_match"

In [18]:
# Re-applying the matching function after its definition

import pandas as pd
from tqdm.auto import tqdm

tqdm.pandas()

resultado_matching = ingredientes[
    "ingredient_standardized_clean"
].progress_apply(
    buscar_match_tcac
)

(
    ingredientes["tcac_codigo"],
    ingredientes["tcac_nombre"],
    ingredientes["match_score"],
    ingredientes["match_method"]
) = zip(*resultado_matching)

ingredientes.head()

  0%|          | 0/3777 [00:00<?, ?it/s]

,recipe_id,recipe_title,ingredient_id,original_text,clean_text,ingredient_name_clean,unit_clean,quantity_original,quantity_value,unit_extracted,...,metric_equivalent_unit,ingredient_standardized,metric_quantity_value,metric_quantity_unit,conversion_method,ingredient_standardized_clean,tcac_codigo,tcac_nombre,match_score,match_method
0,86af61e4-e16a-11ed-9591-a96d6180cd25,Arepas de Queso,1,1 taza de harina de arepa blanca o amarilla,1 taza de harina de arepa blanca o amarilla,harina de arepa blanca o amarilla,taza,1,1.000000,taza,...,NaN,harina de arepa,132.0,g,conversion_volumen_a_gramos_por_densidad,harina de arepa,None,None,NaN,sin_match
1,86af61e4-e16a-11ed-9591-a96d6180cd25,Arepas de Queso,2,1 taza de agua tibia,1 taza de agua tibia,agua tibia,taza,1,1.000000,taza,...,NaN,agua,240.0,g,conversion_volumen_a_gramos_por_densidad,agua,None,None,NaN,sin_match
2,86af61e4-e16a-11ed-9591-a96d6180cd25,Arepas de Queso,3,⅓ taza de queso mozzarella o queso blanco rallado,1/3 taza de queso mozzarella o queso blanco ra...,queso mozzarella o queso blanco rallado,taza,1/3,0.333333,taza,...,NaN,queso mozzarella,48.0,g,conversion_volumen_a_gramos_por_densidad,queso mozzarella,None,None,NaN,sin_match
3,86af61e4-e16a-11ed-9591-a96d6180cd25,Arepas de Queso,4,2 cucharadas de mantequilla,2 cucharadas de mantequilla,mantequilla,cucharada,2,2.000000,cucharadas,...,NaN,mantequilla,28.8,g,conversion_volumen_a_gramos_por_densidad,mantequilla,D015,Mantequilla,100.0,exact
4,86af61e4-e16a-11ed-9591-a96d6180cd25,Arepas de Queso,5,Sal,sal,sal,NaN,1,1.000000,unidad,...,NaN,sal,NaN,NaN,sin_conversion,sal,L015,Sal,100.0,exact

In [19]:
# 12. Validación rápida de matching

print("Métodos de matching:")
display(
    ingredientes["match_method"]
    .value_counts(dropna=False)
)

print("Promedio de similarity score:")
print(
    ingredientes["match_score"]
    .mean()
)

Métodos de matching:

match_method
sin_match    3437
exact         340
Name: count, dtype: int64

Promedio de similarity score:
100.0

In [20]:
# 13. Revisar matches exitosos

matches_exitosos = ingredientes[
    ingredientes["match_method"] != "sin_match"
]

display(
    matches_exitosos[
        [
            "ingredient_standardized",
            "tcac_nombre",
            "match_score",
            "match_method"
        ]
    ].sample(30, random_state=42)
)

,ingredient_standardized,tcac_nombre,match_score,match_method
3198,mantequilla,Mantequilla,100.0,exact
1755,vinagre,Vinagre,100.0,exact
1736,vinagre,Vinagre,100.0,exact
537,sal,Sal,100.0,exact
1805,vinagre,Vinagre,100.0,exact
2657,mantequilla,Mantequilla,100.0,exact
2230,mantequilla,Mantequilla,100.0,exact
3130,aceite de oliva,Aceite de oliva,100.0,exact
3752,aceite de oliva,Aceite de oliva,100.0,exact
327,mantequilla,Mantequilla,100.0,exact
1795,sal,Sal,100.0,exact
2530,aceite de oliva,Aceite de oliva,100.0,exact
2974,arequipe o dulce de leche,Arequipe o dulce de leche,100.0,exact
2002,sal,Sal,100.0,exact
1720,sal,Sal,100.0,exact
2139,sal,Sal,100.0,exact
1764,aceite de oliva,Aceite de oliva,100.0,exact
3710,sal,Sal,100.0,exact
2996,sal,Sal,100.0,exact
94,aceite de oliva,Aceite de oliva,100.0,exact
3160,mantequilla,Mantequilla,100.0,exact
784,aceite de oliva,Aceite de oliva,100.0,exact
2089,mantequilla,Mantequilla,100.0,exact
1765,sal,Sal,100.0,exact
1954,sal,Sal,100.0,exact
1511,mantequilla,Mantequilla,100.0,exact
1706,mantequilla,Mantequilla,100.0,exact
2472,sal,Sal,100.0,exact
1925,mantequilla,Mantequilla,100.0,exact
3610,sal,Sal,100.0,exact

In [21]:
# 14. Revisar ingredientes sin match

sin_match = ingredientes[
    ingredientes["match_method"] == "sin_match"
].copy()

print("Ingredientes sin match:", sin_match.shape[0])

display(
    sin_match[
        [
            "ingredient_standardized",
            "ingredient_standardized_clean"
        ]
    ]
    .drop_duplicates()
    .head(50)
)

Ingredientes sin match: 3437

,ingredient_standardized,ingredient_standardized_clean
0,harina de arepa,harina de arepa
1,agua,agua
2,queso mozzarella,queso mozzarella
5,pollo,pollo
6,aceite vegetal,aceite vegetal
7,cebolla,cebolla
8,pimienton rojo,pimienton rojo
9,ajo,ajo
10,tomate,tomate
11,sazon,sazon
12,comino,comino
13,cilantro,cilantro
15,pimienta,pimienta
16,papa,papa
17,caldo de pollo,caldo de pollo
22,achiote,achiote
23,mazorca de maiz en 3 pieza,mazorca de maiz en 3 pieza
24,agua o mas si es necesario,agua o mas si es necesario
26,carne de cerdo,carne de cerdo
27,carne de res,carne de res
28,platano,platano
30,yuca,yuca
32,cuarto de cucharadita de pimienta,cuarto de cucharadita de pimienta
34,posta o muchacho de 3 a 4 libra gruesa,posta o muchacho de 3 a 4 libra gruesa
35,caldo de carne,caldo de carne
37,salsa de alino ver la receta aqui,salsa de alino ver la receta aqui
41,sal y pimienta,sal y pimienta
46,chorizo,chorizo
49,cebolla larga,cebolla larga
52,lenteja,lenteja
55,zanahoria,zanahoria
62,camaron,camaron
67,carne de bistec falda en 4 porcion igual,carne de bistec falda en 4 porcion igual
70,mostaza,mostaza
72,sal y pimienta negra,sal y pimienta negra
74,hogao ver la receta aqui,hogao ver la receta aqui
77,leche,leche
81,mantequilla para cocinar las arepa,mantequilla para cocinar las arepa
82,salsa de alino ver receta aqui,salsa de alino ver receta aqui
92,carne de falda,carne de falda
100,to mate,to mate
101,salsa negra,salsa negra
102,vino tinto,vino tinto
105,azucar,azucar
108,huevo,huevo
110,harina de trigo para todo uso,harina de trigo para todo uso
111,sazon con color,sazon con color
114,bacalao o trucha,bacalao o trucha
120,harina de trigo,harina de trigo
126,laurel,laurel

In [28]:
# ------------------------------------------------------------
# 15. Actualizar JSON con información TCAC
# ------------------------------------------------------------

import json

input_json = "data/processed/recetas_estructura_json_convertida.json"

with open(input_json, "r", encoding="utf-8") as f:
    recetas_json = json.load(f)

print("JSON cargado:", len(recetas_json))

JSON cargado: 436

In [29]:
# ------------------------------------------------------------
# 16. Crear mapa de matching TCAC
# ------------------------------------------------------------

mapa_tcac = {}

for _, row in ingredientes.iterrows():

    clave = (
        str(row["recipe_id"]),
        int(row["ingredient_id"])
    )

    mapa_tcac[clave] = {
        "tcac_code": None if pd.isna(row["tcac_codigo"]) else row["tcac_codigo"],
        "tcac_food_name": None if pd.isna(row["tcac_nombre"]) else row["tcac_nombre"],
        "match_score": None if pd.isna(row["match_score"]) else float(row["match_score"]),
        "match_method": row["match_method"]
    }

In [30]:
# ------------------------------------------------------------
# 17. Actualizar estructura JSON
# ------------------------------------------------------------

for receta in recetas_json:

    recipe_id = str(receta["recipe_id"])

    for ingrediente in receta["ingredients"]:

        ingredient_id = ingrediente["ingredient_id"]

        clave = (recipe_id, ingredient_id)

        if clave in mapa_tcac:

            ingrediente["tcac_match"] = mapa_tcac[clave]

    receta["pipeline_stage"] = "08_integracion_tcac"
    receta["structure_version"] = "1.3"

print("JSON actualizado correctamente.")

JSON actualizado correctamente.

In [31]:
# ------------------------------------------------------------
# 18. Visualizar ejemplo actualizado
# ------------------------------------------------------------

print(
    json.dumps(
        recetas_json[0],
        ensure_ascii=False,
        indent=2
    )
)

{
  "recipe_id": "86af61e4-e16a-11ed-9591-a96d6180cd25",
  "title": "Arepas de Queso",
  "pipeline_stage": "08_integracion_tcac",
  "structure_version": "1.3",
  "ingredients": [
    {
      "ingredient_id": 1,
      "original_text": "1 taza de harina de arepa blanca o amarilla",
      "clean_text": "1 taza de harina de arepa blanca o amarilla",
      "quantity": {
        "original": "1",
        "value": 1.0
      },
      "unit": {
        "extracted": "taza",
        "clean": "taza"
      },
      "ingredient": {
        "raw": "harina de arepa blanca o amarilla",
        "clean_reference": "harina de arepa blanca o amarilla",
        "standardized": "harina de arepa"
      },
      "preparation_state": null,
      "metric_equivalent": {
        "value": null,
        "unit": null
      },
      "tcac_match": {
        "tcac_code": null,
        "tcac_food_name": null,
        "match_score": null,
        "match_method": "sin_match"
      },
      "metric_quantity": {
        "value": 132.0,
        "unit": "g",
        "method": "conversion_volumen_a_gramos_por_densidad"
      }
    },
    {
      "ingredient_id": 2,
      "original_text": "1 taza de agua tibia",
      "clean_text": "1 taza de agua tibia",
      "quantity": {
        "original": "1",
        "value": 1.0
      },
      "unit": {
        "extracted": "taza",
        "clean": "taza"
      },
      "ingredient": {
        "raw": "agua",
        "clean_reference": "agua tibia",
        "standardized": "agua"
      },
      "preparation_state": "tibia",
      "metric_equivalent": {
        "value": null,
        "unit": null
      },
      "tcac_match": {
        "tcac_code": null,
        "tcac_food_name": null,
        "match_score": null,
        "match_method": "sin_match"
      },
      "metric_quantity": {
        "value": 240.0,
        "unit": "g",
        "method": "conversion_volumen_a_gramos_por_densidad"
      }
    },
    {
      "ingredient_id": 3,
      "original_text": "⅓ taza de queso mozzarella o queso blanco rallado",
      "clean_text": "1/3 taza de queso mozzarella o queso blanco rallado",
      "quantity": {
        "original": "1/3",
        "value": 0.3333333333333333
      },
      "unit": {
        "extracted": "taza",
        "clean": "taza"
      },
      "ingredient": {
        "raw": "queso mozzarella o queso blanco",
        "clean_reference": "queso mozzarella o queso blanco rallado",
        "standardized": "queso mozzarella"
      },
      "preparation_state": "rallado",
      "metric_equivalent": {
        "value": null,
        "unit": null
      },
      "tcac_match": {
        "tcac_code": null,
        "tcac_food_name": null,
        "match_score": null,
        "match_method": "sin_match"
      },
      "metric_quantity": {
        "value": 48.0,
        "unit": "g",
        "method": "conversion_volumen_a_gramos_por_densidad"
      }
    },
    {
      "ingredient_id": 4,
      "original_text": "2 cucharadas de mantequilla",
      "clean_text": "2 cucharadas de mantequilla",
      "quantity": {
        "original": "2",
        "value": 2.0
      },
      "unit": {
        "extracted": "cucharadas",
        "clean": "cucharada"
      },
      "ingredient": {
        "raw": "mantequilla",
        "clean_reference": "mantequilla",
        "standardized": "mantequilla"
      },
      "preparation_state": null,
      "metric_equivalent": {
        "value": null,
        "unit": null
      },
      "tcac_match": {
        "tcac_code": "D015",
        "tcac_food_name": "Mantequilla",
        "match_score": 100.0,
        "match_method": "exact"
      },
      "metric_quantity": {
        "value": 28.799999999999997,
        "unit": "g",
        "method": "conversion_volumen_a_gramos_por_densidad"
      }
    },
    {
      "ingredient_id": 5,
      "original_text": "Sal",
      "clean_text": "sal",
      "quantity": {
        "original": "1",
        "value": 1.0
      },
      "unit": {
        "extracted": "unidad",
        "clean": null
      },
      "ingredient": {
        "raw": "sal",
        "clean_reference": "sal",
        "standardized": "sal"
      },
      "preparation_state": null,
      "metric_equivalent": {
        "value": null,
        "unit": null
      },
      "tcac_match": {
        "tcac_code": "L015",
        "tcac_food_name": "Sal",
        "match_score": 100.0,
        "match_method": "exact"
      },
      "metric_quantity": {
        "value": null,
        "unit": null,
        "method": "sin_conversion"
      }
    }
  ]
}

In [33]:
# ------------------------------------------------------------
# 19. Guardar resultados
# ------------------------------------------------------------

from pathlib import Path

Path("data/interim").mkdir(parents=True, exist_ok=True)
Path("data/processed").mkdir(parents=True, exist_ok=True)
Path("reports/tables").mkdir(parents=True, exist_ok=True)

output_csv = "data/interim/recetas_tcac_integradas.csv"

output_json = (
    "data/processed/"
    "recetas_estructura_json_tcac.json"
)

output_sin_match = (
    "reports/tables/"
    "ingredientes_sin_match_tcac.csv"
)

ingredientes.to_csv(
    output_csv,
    index=False,
    encoding="utf-8-sig"
)

with open(output_json, "w", encoding="utf-8") as f:
    json.dump(
        recetas_json,
        f,
        ensure_ascii=False,
        indent=2
    )

sin_match.to_csv(
    output_sin_match,
    index=False,
    encoding="utf-8-sig"
)

print("Archivos guardados:")
print(output_csv)
print(output_json)
print(output_sin_match)

Archivos guardados:
data/interim/recetas_tcac_integradas.csv
data/processed/recetas_estructura_json_tcac.json
reports/tables/ingredientes_sin_match_tcac.csv

In [34]:
# ------------------------------------------------------------
# 20. Métricas básicas de integración
# ------------------------------------------------------------

total = ingredientes.shape[0]

con_match = ingredientes[
    ingredientes["match_method"] != "sin_match"
].shape[0]

sin_match_n = ingredientes[
    ingredientes["match_method"] == "sin_match"
].shape[0]

cobertura = (con_match / total) * 100

print(f"""
MÉTRICAS DE INTEGRACIÓN TCAC

Total ingredientes: {total}
Ingredientes con match: {con_match}
Ingredientes sin match: {sin_match_n}

Cobertura TCAC:
{cobertura:.2f}%
""")

MÉTRICAS DE INTEGRACIÓN TCAC

Total ingredientes: 3777
Ingredientes con match: 340
Ingredientes sin match: 3437

Cobertura TCAC:
9.00%

# Integración con la TCAC

En esta etapa se realiza la integración entre los ingredientes estandarizados del pipeline y la Tabla de Composición de Alimentos Colombianos (TCAC).

El objetivo es asociar cada ingrediente procesado con el alimento más similar disponible en la TCAC para posteriormente calcular el perfil nutricional de cada receta.

La integración se realiza mediante una estrategia híbrida:

- coincidencia exacta,
- coincidencia normalizada,
- fuzzy matching utilizando RapidFuzz.

Esta etapa utiliza como entrada:

- `data/interim/recetas_unidades_convertidas.csv`
- `data/raw/tcac/tcac.csv`

y actualiza la estructura JSON del pipeline incorporando:

`tcac_match`